/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    App: typeof import('./../src/App.vue')['default']
    ErrorModal: typeof import('./../src/components/errorModal.vue')['default']
    FileUpload: typeof import('./../src/views/fileUpload.vue')['default']
    Home: typeof import('./../src/views/home.vue')['default']
    Layout: typeof import('./../src/layout/layout.vue')['default']
    Login: typeof import('./../src/views/login.vue')['default']
    Navbar: typeof import('./../src/views/navbar.vue')['default']
    RotatingText: typeof import('./../src/components/fantasticCss/rotatingText.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Shudu: typeof import('./../src/views/shudu.vue')['default']
    UserOverView: typeof import('./../src/views/userOverView.vue')['default']
  }
}
